name: Test Workflow
on:
  workflow_call:
    inputs:
        target_folder:
            required: true
            type: string
            default: "blogs"
        meta_path:
            required: true
            type: string
            default: "blog-meta.json"
        branch:
            required: true
            type: string
            default: "blogs"
        echo_arguments:
            required: false
            type: string
            default: ""
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Copy {target_folder} to {target_folder}_copied
              run: |
                rm -rf ${{ inputs.target_folder }}_copied
                cp -rf ${{ inputs.target_folder }} ${{ inputs.target_folder }}_copied
            - name: Copy {meta_path} inside {target_folder}_copied
              run: |
                cp -f ${{ inputs.meta_path }} ${{ inputs.target_folder }}_copied/${{ inputs.meta_path }}
            - name: Print out branch
              run: |
                BRANCH_NAME="I am a branch!"
                if [ -n "${{ inputs.branch }}" ]; then
                    BRANCH_NAME=${{inputs.branch}}
                    if [[ $BRANCH_NAME == "main" ]]; then
                        BRANCH_NAME="I am main!"
                    fi
                fi
                echo "$BRANCH_NAME ${{ inputs.echo_arguments }}"
            - name: Commit new files
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add ${{inputs.target_folder}}_copied/**
                  if git diff --cached --exit-code; then
                    echo "No changes to commit"
                  else
                    git commit -m "Update files"
                    git push
                  fi