name: Push test
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
    test:
        uses: ./.github/workflows/generic-use.yml
        with:
            target_folder: "test"
            meta_path: "test-meta.json"
            branch: "main"
            echo_arguments: "Very Cool!"